var colonies = [
   {"name":"Aeneas",     "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Barren","notes":"Automated Defenses, Mineral Rich","fixed":[]},
   {"name":"Agamemnon",  "capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"Adaptable","notes":"Scattered Survivors, Strategic Resources","fixed":[]},
   {"name":"Ajax",       "capacity":10,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Barren","notes":"Fair Biosphere (x2)","fixed":[]},
   {"name":"Apollo",     "capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Barren","notes":"Ancient Ruins, Fair Biosphere","fixed":[]},
   {"name":"Atlanta",    "capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"Adaptable","notes":"Spy Satellites, Strategic Resources","fixed":[]},
   {"name":"Baldur",     "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":5,"type":"Barren","notes":"Ancient Ruins, Strategic Resources","fixed":[]},
   {"name":"Bellerophon","capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"adaptable","notes":"Automated Defenses, Strategic Resources","fixed":[]},
   {"name":"Cassandra",  "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Barren","notes":"","fixed":[]},
   {"name":"Chimera",    "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":5,"type":"Barren","notes":"Mineral Rich, Strategic Resources","fixed":[]},
   {"name":"Daedalus",   "capacity":4,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"Dead","notes":"Mineral Rich, Strategic Resources","fixed":[]},
   {"name":"Diomedes",   "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Barren","notes":"Ancient Ruins, Spy Satellites","fixed":[]},
   {"name":"Freya",      "capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":6,"type":"Barren","notes":"Fair Biosphere","fixed":[]},
   {"name":"Frigga",     "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Barren","notes":"Mineral Rich, Spy Satellites","fixed":[]},
   {"name":"Hector",     "capacity":2,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Extreme","notes":"Ancient Ruins, Automated Defenses","fixed":[]},
   {"name":"Heimdall",   "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":6,"type":"Barren","notes":"","fixed":[]},
   {"name":"Hela",       "capacity":4,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":6,"type":"Dead","notes":"Ancient Ruins, Automated Defenses","fixed":[]},
   {"name":"Hera",       "capacity":12,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":5,"type":"Homeworld","notes":"","fixed":[]},
   {"name":"Heracles",   "capacity":4,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Dead","notes":"Automated Defenses, Strategic Resources","fixed":[]},
   {"name":"Idis",       "capacity":4,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Dead","notes":"Ancient Ruins","fixed":[]},
   {"name":"Jotunhiem",  "capacity":4,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":1,"type":"Dead","notes":"Spy Satellites","fixed":[]},
   {"name":"Loki",       "capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":5,"type":"Adaptable","notes":"Mineral Rich, Strategic Resources","fixed":[]},
   {"name":"Meleager",   "capacity":2,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":1,"type":"Extreme","notes":"Automated Defenses","fixed":[]},
   {"name":"Menelaus",   "capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"Adaptable","notes":"Ancient Ruins (x2)","fixed":[]},
   {"name":"Midgard",    "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"Barren","notes":"Ancient Ruins, Mineral Rich","fixed":[]},
   {"name":"Odin",       "capacity":12,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":5,"type":"Homeworld","notes":"","fixed":[]},
   {"name":"Odysseus",   "capacity":2,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Extreme","notes":"Ancient Ruins","fixed":[]},
   {"name":"Oedipus",    "capacity":2,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Extreme","notes":"Automated Defenses, Strategic Resources","fixed":[]},
   {"name":"Olympus",    "capacity":12,"fort":4,"intel":6,"morale":8,"owner":"Federation","population":10,"raw":5,"type":"Homeworld","notes":"",
                         "fixed":["Shipyard","Base Station","5xMilitia-II","2xPolice-II","2xLight Infantry"]
   },
   {"name":"Orpheus",    "capacity":10,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"Garden","notes":"Ancient Ruins, Lost Colony","fixed":[]},
   {"name":"Perseus",    "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":4,"type":"Barren","notes":"Spy Satellites, Strategic Resources","fixed":[]},
   {"name":"Priam",      "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Barren","notes":"Spy Satellites","fixed":[]},
   {"name":"Sagittarius","capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Barren","notes":"Ancient Ruins, Automated Defenses","fixed":[]},
   {"name":"Sif",        "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":3,"type":"Barren","notes":"Mineral Rich, Spy Satellites","fixed":[]},
   {"name":"Thor",       "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":6,"type":"Barren","notes":"Mineral Rich, Scattered Survivors","fixed":[]},
   {"name":"Tyr",        "capacity":6,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Barren","notes":"Scattered Survivors, Spy Satellites","fixed":[]},
   {"name":"Ulysses",    "capacity":8,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":2,"type":"Adaptable","notes":"Spy Satellites (x2)","fixed":[]},
   {"name":"Zeus",       "capacity":12,"fort":0,"intel":0,"morale":0,"owner":"","population":0,"raw":5,"type":"Homeworld","notes":"","fixed":[]}
];
var empire = {"empire":"Federation","maintExpense":0,"miscExpense":0,"miscIncome":0,"name":"Emergent Federation","systemIncome":0,"previousEP":0,"techYear":165,"tradeIncome":0,"researchInvested":0};
var events = [];
var fleets = [{"name":"Initial Fleet","location":"Olympus","units":["3xDD","5xFF","SC","2xPOL","Convoy"],"notes":""}];
var game = {"blankOrders":0,"game":"Sample Game","nextDoc":"sample01","monthsPerYear":6,"previousDoc":"","turn":1,"turnSegment":"post"};
var intelProjects = [];
var mapConnections = [
  ["Aeneas", "Diomedes", "Unexplored"], ["Aeneas", "Hera", "Unexplored"],
  ["Aeneas", "Heracles", "Unexplored"], ["Agamemnon", "Hera", "Unexplored"],
  ["Agamemnon", "Sagittarius", "Unexplored"], ["Agamemnon", "Ulysses", "Unexplored"],
  ["Ajax", "Apollo", "Unexplored"], ["Ajax", "Cassandra", "Unexplored"],
  ["Ajax", "Heracles", "Unexplored"], ["Apollo", "Cassandra", "Unexplored"],
  ["Apollo", "Chimera", "Unexplored"], ["Atlanta", "Midgard", "Unexplored"],
  ["Atlanta", "Perseus", "Unexplored"], ["Atlanta", "Priam", "Unexplored"],
  ["Atlanta", "Zeus", "Unexplored"], ["Baldur", "Idis", "Unexplored"],
  ["Baldur", "Jotunhiem", "Unexplored"], ["Baldur", "Loki", "Unexplored"],
  ["Baldur", "Freya", "Unexplored"], ["Bellerophon", "Daedalus", "Unexplored"],
  ["Bellerophon", "Meleager", "Unexplored"], ["Bellerophon", "Oedipus", "Unexplored"],
  ["Bellerophon", "Sagittarius", "Unexplored"], ["Bellerophon", "Ulysses", "Unexplored"],
  ["Cassandra", "Odysseus", "Unexplored"], ["Chimera", "Odysseus", "Unexplored"],
  ["Chimera", "Orpheus", "Unexplored"], ["Chimera", "Priam", "Unexplored"],
  ["Daedalus", "Sagittarius", "Unexplored"], ["Daedalus", "Oedipus", "Unexplored"],
  ["Diomedes", "Heracles", "Unexplored"], ["Diomedes", "Menelaus", "Unexplored"],
  ["Freya", "Frigga", "Unexplored"], ["Freya", "Odin", "Unexplored"],
  ["Frigga", "Tyr", "Unexplored"], ["Hector", "Hera", "Unexplored"],
  ["Hector", "Menelaus", "Unexplored"], ["Heimdall", "Midgard", "Unexplored"],
  ["Heimdall", "Sif", "Unexplored"], ["Hela", "Midgard", "Unexplored"],
  ["Hela", "Sif", "Unexplored"], ["Idis", "Loki", "Unexplored"],
  ["Idis", "Sif", "Unexplored"], ["Jotunhiem", "Midgard", "Unexplored"],
  ["Loki", "Odin", "Unexplored"], ["Menelaus", "Olympus", "Unexplored"],
  ["Menelaus", "Ulysses", "Unexplored"], ["Odin", "Thor", "Unexplored"],
  ["Odysseus", "Zeus", "Unexplored"], ["Oedipus", "Tyr", "Unexplored"],
  ["Olympus", "Orpheus", "Unexplored"], ["Olympus", "Priam", "Unexplored"],
  ["Perseus", "Zeus", "Unexplored"], ["Thor", "Tyr", "Unexplored"]
];
var mapPoints = [
   [70,300,"","Aeneas"], [70,180,"","Agamemnon"], [140,420,"","Ajax"],
   [175,360,"","Apollo"], [315,360,"","Atlanta"], [350,180,"","Baldur"],
   [175,120,"","Bellerophon"], [210,420,"","Cassandra"], [245,360,"","Chimera"],
   [140,60,"","Daedalus"], [140,300,"","Diomedes"], [315,120,"","Freya"],
   [280,180,"","Frigga"], [105,240,"","Hector"], [420,300,"","Heimdall"],
   [385,240,"","Hela"], [35,240,"Orion","Hera"], [105,360,"","Heracles"],
   [420,180,"","Idis"], [315,240,"","Jotunhiem"], [385,120,"","Loki"],
   [210,180,"","Meleager"], [175,240,"","Menelaus"], [350,300,"","Midgard"],
   [350,60,"Orion","Odin"], [280,420,"","Odysseus"], [210,60,"","Oedipus"],
   [245,240,"Federation","Olympus"], [210,300,"","Orpheus"], [385,360,"","Perseus"],
   [280,300,"","Priam"], [105,120,"","Sagittarius"], [455,240,"","Sif"],
   [280,60,"","Thor"], [245,120,"","Tyr"], [140,180,"","Ulysses"],
   [350,420,"Orion","Zeus"]
];
var offeredTreaties = [];
var orders = [];
var otherEmpires = [];
var purchases = [];
var treaties = [];
var underConstruction = [];
var unitStates = [];
var unitsInMothballs = [];
var unitsNeedingRepair = [];
var unknownMovementPlaces = [];
var unitList = [
// Ships
   {"ship":"OCA","yis":125,"design":"CA","cost":14,"notes":""},
   {"ship":"CLS","yis":125,"design":"CL","cost":11,"notes":"Scout(2)"},
   {"ship":"CMC","yis":125,"design":"CL","cost":9,"notes":"Assault(2), Atmospheric"},
   {"ship":"FF","yis":127,"design":"FF","cost":8,"notes":""},
   {"ship":"POL","yis":127,"design":"POL","cost":6,"notes":"Police"},
   {"ship":"CA","yis":130,"design":"CA","cost":14,"notes":""},
   {"ship":"LSC","yis":130,"design":"CL","cost":12,"notes":"Scout(4)"},
   {"ship":"SC","yis":130,"design":"DD","cost":11,"notes":"Scout(4)"},
   {"ship":"YCA","yis":132,"design":"CA","cost":9,"notes":""},
   {"ship":"YDD","yis":132,"design":"DD","cost":5,"notes":""},
   {"ship":"TUG","yis":135,"design":"TUG","cost":7,"notes":"Supply(3)"},
   {"ship":"GSC","yis":140,"design":"CA","cost":14,"notes":"Scout(1)"},
   {"ship":"GSR","yis":140,"design":"CA","cost":9,"notes":"Scout(1)"},
   {"ship":"CLH","yis":140,"design":"CL","cost":8,"notes":""},
   {"ship":"FFT","yis":140,"design":"FF","cost":6,"notes":"Supply(1)"},
   {"ship":"FFP","yis":140,"design":"FF","cost":6,"notes":"Supply(1)"},
   {"ship":"CC","yis":143,"design":"CA","cost":15,"notes":"Command"},
   {"ship":"BT","yis":145,"design":"TUG","cost":19,"notes":"Supply(3)"},
   {"ship":"FEM","yis":145,"design":"DD","cost":7,"notes":""},
   {"ship":"DN","yis":148,"design":"DN","cost":20,"notes":""},
   {"ship":"CFF","yis":150,"design":"FF","cost":6,"notes":"Assault(1)"},
   {"ship":"DD","yis":160,"design":"DD","cost":10,"notes":""},
   {"ship":"CS","yis":165,"design":"CA","cost":14,"notes":""},
   {"ship":"FFL","yis":165,"design":"FF","cost":8,"notes":""},
   {"ship":"DDL","yis":166,"design":"DD","cost":10,"notes":""},
   {"ship":"DNL","yis":167,"design":"DNL","cost":27,"notes":"Fast"},
   {"ship":"CF","yis":167,"design":"CA","cost":18,"notes":"Fast"},
   {"ship":"CVL","yis":167,"design":"CA","cost":18,"notes":"Carrier(6), Scout(1)"},
   {"ship":"DDF","yis":167,"design":"DD","cost":12,"notes":"Fast"},
   {"ship":"DDG","yis":167,"design":"DD","cost":10,"notes":""},
   {"ship":"CVS","yis":168,"design":"CA","cost":16,"notes":"Carrier(12)"},
   {"ship":"DE","yis":168,"design":"DD","cost":11,"notes":""},
   {"ship":"FFR","yis":168,"design":"FF","cost":9,"notes":""},
   {"ship":"FFE","yis":168,"design":"FF","cost":9,"notes":""},
   {"ship":"FFD","yis":168,"design":"FF","cost":8,"notes":""},
   {"ship":"GVM","yis":169,"design":"CA","cost":12,"notes":"Carrier(12)"},
   {"ship":"CLV","yis":169,"design":"CL","cost":10,"notes":"Carrier(12)"},
   {"ship":"GDE","yis":169,"design":"DD","cost":9,"notes":""},
   {"ship":"BTV","yis":170,"design":"TUG","cost":23,"notes":"Carrier(12)"},
   {"ship":"COV","yis":170,"design":"CA","cost":17,"notes":"Assault(2), Scout(1)"},
   {"ship":"NCL","yis":170,"design":"CW","cost":13,"notes":""},
   {"ship":"POV","yis":170,"design":"POL","cost":6,"notes":"Carrier(6), Police"},
   {"ship":"FFS","yis":170,"design":"FF","cost":6,"notes":"Scout(1)"},
   {"ship":"CVA","yis":171,"design":"DN","cost":22,"notes":"Carrier(24)"},
   {"ship":"NCD","yis":171,"design":"CW","cost":13,"notes":""},
   {"ship":"ECL","yis":171,"design":"CL","cost":11,"notes":""},
   {"ship":"CVB","yis":172,"design":"CA","cost":17,"notes":"Carrier(12)"},
   {"ship":"CAD","yis":172,"design":"CA","cost":16,"notes":"Scout(1)"},
   {"ship":"CVTC","yis":172,"design":"TUG","cost":14,"notes":"Carrier(36)"},
   {"ship":"CVE","yis":172,"design":"CL","cost":11,"notes":"Carrier(4), Scout(2)"},
   {"ship":"CVT","yis":172,"design":"TUG","cost":10,"notes":"Carrier(24), Supply(3)"},
   {"ship":"FFV","yis":172,"design":"FF","cost":6,"notes":"Carrier(6)"},
   {"ship":"DVL","yis":173,"design":"DNL","cost":25,"notes":"Carrier(12), Fast"},
   {"ship":"CVF","yis":173,"design":"CA","cost":15,"notes":"Carrier(12), Fast"},
   {"ship":"CVD","yis":173,"design":"CA","cost":13,"notes":"Carrier(24)"},
   {"ship":"CVP","yis":173,"design":"CW","cost":12,"notes":"Carrier(18)"},
   {"ship":"CLD","yis":173,"design":"CL","cost":12,"notes":"Scout(2)"},
   {"ship":"NEC","yis":173,"design":"CW","cost":11,"notes":""},
   {"ship":"NCT","yis":173,"design":"CW","cost":11,"notes":"Assault(2)"},
   {"ship":"NVL","yis":173,"design":"CW","cost":11,"notes":"Carrier(12)"},
   {"ship":"DER","yis":173,"design":"DD","cost":10,"notes":""},
   {"ship":"FCR","yis":173,"design":"FF","cost":6,"notes":""},
   {"ship":"BTL","yis":174,"design":"TUG","cost":16,"notes":"Supply(3)"},
   {"ship":"LBT","yis":174,"design":"CW","cost":16,"notes":""},
   {"ship":"LTV","yis":174,"design":"CW","cost":15,"notes":"Carrier(12)"},
   {"ship":"LTT","yis":174,"design":"CW","cost":8,"notes":"Supply(2)"},
   {"ship":"DNG","yis":175,"design":"DN","cost":27,"notes":""},
   {"ship":"NCC","yis":175,"design":"NCA","cost":19,"notes":"Command"},
   {"ship":"CB","yis":175,"design":"CA","cost":18,"notes":""},
   {"ship":"NCF","yis":175,"design":"NCA","cost":18,"notes":""},
   {"ship":"NCV","yis":175,"design":"NCA","cost":17,"notes":"Carrier(12)"},
   {"ship":"NDC","yis":175,"design":"NCA","cost":17,"notes":""},
   {"ship":"NCA","yis":175,"design":"NCA","cost":16,"notes":""},
   {"ship":"CLC","yis":175,"design":"CW","cost":16,"notes":"Command"},
   {"ship":"NLF","yis":175,"design":"CW","cost":15,"notes":"Fast"},
   {"ship":"NVS","yis":175,"design":"CW","cost":14,"notes":"Carrier(12)"},
   {"ship":"NAC","yis":175,"design":"CW","cost":14,"notes":""},
   {"ship":"NER","yis":175,"design":"CW","cost":13,"notes":""},
   {"ship":"NEA","yis":175,"design":"CW","cost":13,"notes":""},
   {"ship":"ACL","yis":175,"design":"CL","cost":13,"notes":""},
   {"ship":"NSR","yis":175,"design":"NCA","cost":13,"notes":"Scout(1)"},
   {"ship":"DEA","yis":175,"design":"DD","cost":12,"notes":""},
   {"ship":"DAR","yis":175,"design":"DD","cost":11,"notes":""},
   {"ship":"FBE","yis":175,"design":"DW","cost":11,"notes":""},
   {"ship":"FFB","yis":175,"design":"DW","cost":10,"notes":""},
   {"ship":"FFA","yis":175,"design":"FF","cost":10,"notes":""},
   {"ship":"FRA","yis":175,"design":"FF","cost":10,"notes":""},
   {"ship":"FBD","yis":175,"design":"DW","cost":10,"notes":""},
   {"ship":"PFF","yis":175,"design":"FF","cost":9,"notes":""},
   {"ship":"FBS","yis":175,"design":"DW","cost":9,"notes":"Scout(2)"},
   {"ship":"FBV","yis":175,"design":"DW","cost":7,"notes":"Carrier(6)"},
   {"ship":"FXE","yis":175,"design":"FF","cost":3,"notes":"Atmospheric, Fast"},
   {"ship":"CFS","yis":176,"design":"CA","cost":16,"notes":"Fast, Scout(4)"},
   {"ship":"DWA","yis":176,"design":"DW","cost":12,"notes":""},
   {"ship":"DWR","yis":176,"design":"DW","cost":12,"notes":""},
   {"ship":"DWC","yis":176,"design":"DW","cost":12,"notes":""},
   {"ship":"PV","yis":176,"design":"POL","cost":11,"notes":"Carrier(12), Police"},
   {"ship":"DW","yis":176,"design":"DW","cost":11,"notes":""},
   {"ship":"NSC","yis":176,"design":"CW","cost":11,"notes":"Scout(3)"},
   {"ship":"DWD","yis":176,"design":"DW","cost":11,"notes":""},
   {"ship":"DWS","yis":176,"design":"DW","cost":10,"notes":"Scout(2)"},
   {"ship":"ADW","yis":176,"design":"DW","cost":9,"notes":"Carrier(3H), Scout(1)"},
   {"ship":"DWT","yis":176,"design":"DW","cost":7,"notes":""},
   {"ship":"GVH","yis":177,"design":"CA","cost":45,"notes":"Carrier(6H)"},
   {"ship":"BCG","yis":177,"design":"BC","cost":20,"notes":""},
   {"ship":"CVH","yis":177,"design":"CA","cost":18,"notes":"Carrier(6H)"},
   {"ship":"CAV","yis":177,"design":"CA","cost":17,"notes":""},
   {"ship":"NHS","yis":177,"design":"NCA","cost":15,"notes":"Scout(4)"},
   {"ship":"NHA","yis":177,"design":"NCA","cost":14,"notes":"Scout(1)"},
   {"ship":"NHV","yis":177,"design":"NCA","cost":14,"notes":"Carrier(6H), Scout(1)"},
   {"ship":"NDS","yis":177,"design":"NCA","cost":13,"notes":"Carrier(12+6H), Scout(2)"},
   {"ship":"DWV","yis":177,"design":"DW","cost":12,"notes":"Carrier(8)"},
   {"ship":"CSV","yis":177,"design":"CW","cost":12,"notes":"Carrier(6H), Scout(2)"},
   {"ship":"NVH","yis":177,"design":"CW","cost":10,"notes":"Carrier(6H), Scout(1)"},
   {"ship":"NVA","yis":177,"design":"CW","cost":10,"notes":"Carrier(6H), Scout(1)"},
   {"ship":"PDD","yis":177,"design":"DD","cost":8,"notes":""},
   {"ship":"IPL","yis":177,"design":"POL","cost":7,"notes":"Police"},
   {"ship":"COR","yis":177,"design":"POL","cost":7,"notes":"Police, Slow"},
   {"ship":"DNH","yis":178,"design":"DN","cost":29,"notes":""},
   {"ship":"BCF","yis":178,"design":"BC","cost":20,"notes":""},
   {"ship":"DCS","yis":178,"design":"CA","cost":12,"notes":"Carrier(12+6H), Scout(2)"},
   {"ship":"FCA","yis":178,"design":"DW","cost":8,"notes":""},
   {"ship":"FCF","yis":178,"design":"DW","cost":8,"notes":""},
   {"ship":"CDW","yis":178,"design":"DW","cost":8,"notes":"Assault(1)"},
   {"ship":"DNF","yis":179,"design":"DN","cost":27,"notes":""},
   {"ship":"DVA","yis":179,"design":"DN","cost":26,"notes":"Carrier(12+6H)"},
   {"ship":"NSV","yis":180,"design":"NCA","cost":14,"notes":"Scout(3)"},
   {"ship":"HDW","yis":180,"design":"HDW","cost":13,"notes":""},
   {"ship":"CX","yis":181,"design":"CA","cost":27,"notes":"Fast"},
   {"ship":"GVX","yis":182,"design":"CA","cost":25,"notes":"Carrier(6H), Fast, Scout(1)"},
   {"ship":"HDWX","yis":182,"design":"HDW","cost":20,"notes":"Fast"},
   {"ship":"DDX","yis":182,"design":"DD","cost":19,"notes":"Fast"},
   {"ship":"DGX","yis":182,"design":"DD","cost":18,"notes":"Fast"},
   {"ship":"NAX","yis":183,"design":"NCA","cost":25,"notes":"Fast, Scout(1)"},
   {"ship":"BCV","yis":183,"design":"BC","cost":22,"notes":"Carrier(12)"},
   {"ship":"NASX","yis":183,"design":"NCA","cost":20,"notes":"Fast"},
   {"ship":"DWX","yis":183,"design":"DW","cost":17,"notes":"Fast"},
   {"ship":"SCX","yis":183,"design":"DD","cost":14,"notes":"Fast, Scout(1)"},
   {"ship":"FFX","yis":183,"design":"FF","cost":12,"notes":"Fast"},
   {"ship":"HVX","yis":184,"design":"CA","cost":27,"notes":"Fast"},
   {"ship":"BCS","yis":184,"design":"BC","cost":23,"notes":"Carrier(6+6H)"},
   {"ship":"SCS","yis":186,"design":"DN","cost":25,"notes":"Carrier(24+6H)"},
   {"ship":"BCJ","yis":186,"design":"BC","cost":22,"notes":""},
   {"ship":"GSX","yis":186,"design":"CA","cost":22,"notes":"Fast, Scout(1)"},
   {"ship":"Early Base Station","yis":65,"design":"BSE","cost":15,"notes":"Fixed"},
   {"ship":"Early Base Station-I","yis":105,"design":"BSE","cost":16,"notes":"Fixed, Supply Depot"},
   {"ship":"Base Station","yis":120,"design":"BS","cost":18,"notes":"Fixed, Scout(1), Supply Depot"},
   {"ship":"Base Station-I","yis":160,"design":"BS","cost":18,"notes":"Carrier(12), Fixed, Scout(2), Supply Depot"},
   {"ship":"Base Station-II","yis":185,"design":"BS","cost":18,"notes":"Carrier(12), Fixed, Scout(2), Supply Depot"},
   {"ship":"Battle Station","yis":130,"design":"BATS","cost":24,"notes":"Carrier(12), Fixed, Scout(2), Supply Depot"},
   {"ship":"Battle Station-I","yis":170,"design":"BATS","cost":24,"notes":"Carrier(12), Fixed, Scout(4), Supply Depot"},
   {"ship":"Battle Station-II","yis":190,"design":"BATS","cost":24,"notes":"Carrier(12), Fixed, Scout(4), Supply Depot"},
   {"ship":"StarBase","yis":140,"design":"SB","cost":36,"notes":"Carrier(24), Fixed, Scout(6), Supply Depot"},
   {"ship":"StarBase-I","yis":180,"design":"SB","cost":36,"notes":"Carrier(24), Fixed, Scout(6), Supply Depot"},
   {"ship":"Mobile Base","yis":140,"design":"MB","cost":9,"notes":"Carrier(6), Fixed, Scout(1), Supply Depot"},
   {"ship":"Mobile Base-I","yis":180,"design":"MB","cost":9,"notes":"Carrier(6), Fixed, Scout(1), Supply Depot"},
   {"ship":"Convoy","yis":65,"design":"","cost":20,"notes":"Civilian"},
   {"ship":"Convoy-I","yis":105,"design":"","cost":20,"notes":"Civilian"},
   {"ship":"Convoy-II","yis":145,"design":"","cost":20,"notes":"Civilian"},
   {"ship":"Convoy-III","yis":185,"design":"","cost":20,"notes":"Civilian"},
   {"ship":"Shipyard","yis":65,"design":"Shipyard","cost":20,"notes":"Civilian, Fixed"},
   {"ship":"Shipyard-I","yis":105,"design":"Shipyard","cost":20,"notes":"Civilian, Fixed"},
   {"ship":"Shipyard-II","yis":145,"design":"Shipyard","cost":20,"notes":"Civilian, Fixed"},
   {"ship":"Shipyard-III","yis":185,"design":"Shipyard","cost":20,"notes":"Civilian, Fixed"},
   {"ship":"Supply Depot","yis":65,"design":"Depot","cost":20,"notes":"Civilian, Fixed, Supply Depot"},
   {"ship":"Supply Depot-I","yis":105,"design":"Depot","cost":20,"notes":"Civilian, Fixed, Supply Depot"},
   {"ship":"Supply Depot-II","yis":145,"design":"Depot","cost":20,"notes":"Civilian, Fixed, Supply Depot"},
   {"ship":"Supply Depot-III","yis":185,"design":"Depot","cost":20,"notes":"Civilian, Fixed, Supply Depot"},
   {"ship":"F-8","yis":167,"design":"LF","cost":2,"notes":""},
   {"ship":"F-104A","yis":167,"design":"LF","cost":2,"notes":""},
   {"ship":"F-4","yis":167,"design":"LF","cost":2,"notes":""},
   {"ship":"F-7","yis":167,"design":"LF","cost":1,"notes":""},
   {"ship":"A-6A","yis":168,"design":"LF","cost":3,"notes":""},
   {"ship":"F-104G","yis":170,"design":"LF","cost":2,"notes":""},
   {"ship":"F-14","yis":171,"design":"LF","cost":3,"notes":""},
   {"ship":"A-10","yis":171,"design":"LF","cost":3,"notes":""},
   {"ship":"F-104J","yis":172,"design":"LF","cost":3,"notes":""},
   {"ship":"F-15","yis":172,"design":"LF","cost":3,"notes":""},
   {"ship":"F-16","yis":173,"design":"LF","cost":2,"notes":""},
   {"ship":"F-18","yis":173,"design":"LF","cost":2,"notes":""},
   {"ship":"F-104S","yis":175,"design":"LF","cost":3,"notes":""},
   {"ship":"F-20","yis":175,"design":"LF","cost":2,"notes":""},
   {"ship":"F-101A","yis":176,"design":"HF","cost":4,"notes":""},
   {"ship":"F-111","yis":177,"design":"HF","cost":5,"notes":""},
   {"ship":"A-20","yis":177,"design":"HF","cost":5,"notes":""},
   {"ship":"F-14A","yis":177,"design":"LF","cost":4,"notes":""},
   {"ship":"A-20F","yis":179,"design":"HF","cost":5,"notes":""},
   {"ship":"E-3A","yis":180,"design":"HF","cost":7,"notes":""},
   {"ship":"E-2A","yis":180,"design":"LF","cost":4,"notes":""},
   {"ship":"A-6F","yis":180,"design":"LF","cost":3,"notes":""},
   {"ship":"Militia","yis":65,"design":"Ground Unit","cost":1,"notes":"Garrison"},
   {"ship":"Militia-I","yis":105,"design":"Ground Unit","cost":1,"notes":"Garrison"},
   {"ship":"Militia-II","yis":145,"design":"Ground Unit","cost":1,"notes":"Garrison"},
   {"ship":"Militia-III","yis":185,"design":"Ground Unit","cost":1,"notes":"Garrison"},
   {"ship":"Police","yis":65,"design":"Ground Unit","cost":1,"notes":"Peacekeeper"},
   {"ship":"Police-I","yis":105,"design":"Ground Unit","cost":1,"notes":"Peacekeeper"},
   {"ship":"Police-II","yis":145,"design":"Ground Unit","cost":1,"notes":"Peacekeeper"},
   {"ship":"Police-III","yis":185,"design":"Ground Unit","cost":1,"notes":"Peacekeeper"},
   {"ship":"Prime Team","yis":65,"design":"Ground Unit","cost":2,"notes":"Special Forces"},
   {"ship":"Prime Team-I","yis":105,"design":"Ground Unit","cost":2,"notes":"Special Forces"},
   {"ship":"Prime Team-II","yis":145,"design":"Ground Unit","cost":2,"notes":"Special Forces"},
   {"ship":"Prime Team-III","yis":185,"design":"Ground Unit","cost":2,"notes":"Special Forces"},
   {"ship":"Light Infantry","yis":65,"design":"Ground Unit","cost":1,"notes":"Marines"},
   {"ship":"Light Infantry-I","yis":105,"design":"Ground Unit","cost":1,"notes":"Marines"},
   {"ship":"Light Infantry-II","yis":145,"design":"Ground Unit","cost":1,"notes":"Marines"},
   {"ship":"Light Infantry-III","yis":185,"design":"Ground Unit","cost":1,"notes":"Marines"},
   {"ship":"Light Armor","yis":65,"design":"Ground Unit","cost":2,"notes":""},
   {"ship":"Light Armor-I","yis":105,"design":"Ground Unit","cost":2,"notes":""},
   {"ship":"Light Armor-II","yis":145,"design":"Ground Unit","cost":2,"notes":""},
   {"ship":"Light Armor-III","yis":185,"design":"Ground Unit","cost":2,"notes":""},
   {"ship":"Heavy Armor","yis":65,"design":"Ground Unit","cost":3,"notes":""},
   {"ship":"Heavy Armor-I","yis":105,"design":"Ground Unit","cost":3,"notes":""},
   {"ship":"Heavy Armor-II","yis":145,"design":"Ground Unit","cost":3,"notes":""},
   {"ship":"Heavy Armor-III","yis":185,"design":"Ground Unit","cost":3,"notes":""}
];
